Formatting the source code to comply with the LLVM standard
felix642/1chipML pull request #29
Opened 2023-01-20 20:55 UTC by nicholaslegrand102

I created a .clang-format file that complies with the LLVM standard that was used to format all of the code. 

Closes issue #28

2023-01-20 20:59 UTC, felix642 commented
@nicholaslegrand102 you've requested my review on this PR, but this is still marked as a draft. I'm a bit confused, am I supposed to review this PR or not? 🙃

2023-01-20 20:59 UTC, felix642 commented on src/.clang-format
> +Language:        Cpp
Hmm, that's not right

2023-01-20 21:55 UTC, felix642 commented on src/.clang-format
> +AccessModifierOffset: -2
This is not something that exists in C.

2023-01-20 21:57 UTC, felix642 requested changes
Hi @nicholaslegrand102 I left a few comments. Would you mind taking a look ? :)

2023-01-20 21:57 UTC, felix642 commented on src/.clang-format
> +UseCRLF:         false
I do not think we need this option.

2023-01-20 21:57 UTC, felix642 commented on src/.clang-format
> +PointerAlignment: Right
I vote to align pointers in the middle. @bisson2000 is agreeing with me.

2023-01-20 22:07 UTC, nicholaslegrand102 commented on src/.clang-format
> +AccessModifierOffset: -2
good point

2023-01-20 22:10 UTC, nicholaslegrand102 commented on src/.clang-format
> +UseCRLF:         false
Why not?

2023-01-20 23:00 UTC, felix642 approved these changes
LGTM 👍🏿

2023-01-22 12:08 UTC, bisson2000 approved these changes
lgtm

2023-01-22 15:52 UTC, merged

2023-01-22 15:54 UTC, felix642 commented
Thank you @nicholaslegrand102. I have merged your PR in the main branch. Feel free to open a PR on the official repo now.