Implemented Lanczos Algorithm
felix642/1chipML pull request #35
Opened 2023-01-28 02:49 UTC by felix642

closes #19

2023-01-28 04:07 UTC, nicholaslegrand102 reviewed
General question for you . Why did you add the 1chiML logo in a new resources folder. If i look at the original pdf it already had the image.

2023-01-28 13:17 UTC, bisson2000 requested changes

2023-01-28 13:17 UTC, bisson2000 commented on src/lanczos.h
> +void lanczos(double* matrix, int dim, double* tMatrix, double* vMatrix, int nbIter);
Please add 
```
#ifdef __cplusplus
extern "C" {
#endif
```
at the start of your header file and
```
#ifdef __cplusplus
}
#endif
```
at the end of your header file so it works with arduino IDE

2023-01-28 13:17 UTC, bisson2000 commented on src/lanczos.c
> +#include <math.h>
I think string and stdio.h can be removed.
I think includes should be placed in the header file

2023-01-28 15:09 UTC, bisson2000 commented on doc/1chipML_manual.tex
> +  Once the eigenvectors and eigenvalues of T are know, the eigenvectors of the original matrix can be approximated by linear combinations of the Lanczos basis vectors. For example, given an eigenvect
".. are known .. "

2023-01-28 16:23 UTC, felix642 commented
> General question for you . Why did you add the 1chiML logo in a new resources folder. If i look at the original pdf it already had the image.

Hi @nicholaslegrand102, the image used in the .pdf is not part of this repository for some reason. Which means that I can't compile the .tex file into a pdf. 

There might be another image elsewhere that I can use, but I don't know where this could be.

2023-01-28 16:26 UTC, felix642 commented on src/lanczos.c
> +#include <math.h>
Hi @bisson2000, 

The header file "stdio.h" can be remove, but I need to keep "string.h" since it is required for memcpy()
 
https://man7.org/linux/man-pages/man3/memcpy.3.html

2023-01-28 16:27 UTC, felix642 commented on doc/1chipML_manual.tex
> +  Once the eigenvectors and eigenvalues of T are know, the eigenvectors of the original matrix can be approximated by linear combinations of the Lanczos basis vectors. For example, given an eigenvect
Good catch! :)

2023-01-28 16:35 UTC, felix642 commented on src/lanczos.h
> +void lanczos(double* matrix, int dim, double* tMatrix, double* vMatrix, int nbIter);
I'll wait for now. We still don't know which IDE we are supporting and how we are supposed to compile the library.

I'll leave this comment unresolved and once we have more info I will apply the necessary changes.

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static void matrixMultiply(double* firstMatrix, double* secondMatrix, int* size, double* output)
Might be me, but I thought we were supposed to use snake_case since we are programming in C

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +    for(int j = 0; j < size[2]; ++j)
might be necessary to explain the array size, since it's not really clear that the array should contain the number of rows of the first matrix, the number of columns of the second matrix and the number of columns of the second matrix

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +      double tmp = 0;
really picky, but could initialize the value of the output matrix at that element to 0 and add the value to avoid using an unnecessary variable since we are trying to save memory

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static double computeNorm(double* vector, int length)
We should use a typedef that maps a real number to its implementation an a specific board, but since it is not currently implemented, we should at least add a file that does the mapping

```
typedef real double;
```

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static void vectorDivision(double* vector, int nbElements, double scale)
I would call it `scale_vector` and multiply instead of dividing (a user would then put a fraction if a division is needed). I think it's more intuitive to have a scale than a divide

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static void vectorDot(double* vector, int nbElements, double scalar)
just saw that function. I would delete the other function that divides. These functions are basically doing the same thing and they just take twice memory on the chip

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static void vectorSubstract(double* vector1, double* vector2, double* output, int dim)
i would either put the result of the substraction in the first vector to avoid passing another vector or use an output vector with every function above no ?.

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +static void makeUnitVector(double *vector, int nbElements)
asterisk on the right

2023-01-30 00:54 UTC, GM07 commented on src/lanczos.c
> +    {
picky, but curly brackets at new line when the just underneath it's at the end of the line

2023-01-30 03:42 UTC, nicholaslegrand102 commented on src/lanczos.c
> +static void matrixMultiply(double* firstMatrix, double* secondMatrix, int* size, double* output)
The LLVM standard prefers camelCase

2023-01-30 13:05 UTC, felix642 commented on src/lanczos.c
> +static void makeUnitVector(double *vector, int nbElements)
Let's not look at the style for now, we haven't merged the .clang-format in the official repo yet so I haven't had a chance to format my code. There might be a lot of those issues. I'll let you know when the code as been formatted so that you can take a proper look at the style. 

Does that sounds good to you ?

2023-01-30 13:05 UTC, felix642 commented on src/lanczos.c
> +    {
Same as above

2023-01-30 18:31 UTC, GM07 commented on src/lanczos.c
> +static double computeNorm(double* vector, int length)
Yeah for now add it to the lanczos.h file while we create a file to handle the types for all files

2023-01-30 18:31 UTC, GM07 commented on src/lanczos.c
> +static void makeUnitVector(double *vector, int nbElements)
yeahh fair enough

2023-01-31 02:05 UTC, felix642 commented on src/lanczos.c
> +      double tmp = 0;
That's interesting, I added this variable to hint the compiler that the value could be stored in a register. Since we're not optimizing with -O3 it doesn't seem to be listening and we end up using more memory on the stack than what you propose (20 bytes rather than 12).
While taking a look at this I realized a few things:

1- AVR is only able to compare one byte at a time. This means that if we use a for loop with a 2+ bytes variable it requires 3 cycles to compare the values (2 for the comparison and 1 for the jump).
2- AVR has a total of 32 registers of one byte. r0 and r1 seem to be reserved for something specific and we need to keep 2 registers for the stack pointer, 2 registers for X, 2 registers for Y, and 2 registers for Z. This means that we can squeeze at most 22 bytes of data in registers. 

With this information, I was able to optimize a bit my code and store everything in registers. This means that we don't have to grow at all the stack (Yay?)
Here's my implementation, let me know what you think: https://godbolt.org/z/KjbMP1br5
Here's also the implementation that you proposed that requires to grow the stack by 12 bytes:  https://godbolt.org/z/6487YvYMe

The only limitation with the implementation that I propose above is that the maximum size of a matrix would be 255x255 but storing this in memory would require ~256K x 3 matrices = ~768KB which is way above what most microcontrollers can support and I assume that we don't want to support matrices above this size?

2023-01-31 22:03 UTC, felix642 commented on src/lanczos.c
> +static void matrixMultiply(double* firstMatrix, double* secondMatrix, int* size, double* output)
@GM07 This is the only comment left on this PR for now. Can we close it or do we need to make the changes ?

2023-01-31 22:07 UTC, nicholaslegrand102 approved these changes

2023-02-01 18:12 UTC, GM07 approved these changes

2023-02-02 14:36 UTC, bisson2000 approved these changes

2023-02-03 21:15 UTC, felix642 commented
@GM07 I was thinking about making a PCA to demonstrate something that we could do with this algorithm. But this requires Jacobi to properly compute eigenvectors and eigenvalues.  I think we should start by merging this branch first and when your branch will be ready we'll make a third PR with the implementation of PCA. What do you think?

2023-02-03 23:10 UTC, bisson2000 commented on doc/1chipML_manual.tex
> +\includegraphics[width=0.3\textwidth]{resources/1chipML_logo.png}
Use the svp instead if possible

2023-02-03 23:17 UTC, felix642 commented on doc/1chipML_manual.tex
> +\includegraphics[width=0.3\textwidth]{resources/1chipML_logo.png}
Understandable

2023-02-04 16:15 UTC, felix642 commented on doc/1chipML_manual.tex
> +\includegraphics[width=0.3\textwidth]{resources/1chipML_logo.png}
SVG is not supported by latex. 

What should we do?

2023-02-05 00:31 UTC, bisson2000 commented on doc/1chipML_manual.tex
> +\includegraphics[width=0.3\textwidth]{resources/1chipML_logo.png}
Try `\usepackage{svg}`

2023-02-05 17:25 UTC, bisson2000 approved these changes
lgtm

2023-02-16 01:03 UTC, closed without merging