Formatted source code under the LLVM format (#29)
felix642/1chipML pull request #37
Opened 2023-02-02 02:19 UTC by bisson2000

2023-02-02 12:56 UTC, felix642 commented
You have an invalid commit on this PR @bisson2000 fc4d1112ff3b8aa09dd045d04417df1dabe3d35c

2023-02-02 16:46 UTC, felix642 commented on tests/test_FFT.c
> +#include "../src/FFT.h"
When compiling we are adding
"-I./src" to the command line. This tells the compiler to add the folder src to the include folders list.

So you can include fft.h using 
`#include <fft.h>`
This makes sense since in this case this is supposed to be considered an external dependency.

2023-02-02 16:48 UTC, felix642 commented on tests/test_FFT.c
> +  fft_real* outputReals = calloc(length, sizeof(fft_real));
I see that you are allocating memory in the heap and freeing it at the end of this function which is basically what the stack does. But I also just realized that this PR is marked as a draft so I'll wait a bit before reviewing the rest.

2023-02-03 21:50 UTC, felix642 requested changes
Hi @bisson2000, I left a few comments. 🙃

2023-02-03 21:50 UTC, felix642 commented on doc/1chipML_manual.tex
> +%\includegraphics[width=0.3\textwidth]{1chipML_logo.eps}
This will need to be resolved before merging this PR.

2023-02-03 21:50 UTC, felix642 commented on src/DFT.c
> +  memset(outputReals, 0.0, length * sizeof(dft_real));
The signature of memset is the following : `void* memset(void* s, int c, size_t n);`

This means that the second argument is implicitly converted to int.

2023-02-03 21:50 UTC, felix642 commented on src/DFT.c
> +  for (unsigned i = 0; i < length; ++i) {
memcpy() would be faster here.

2023-02-03 21:50 UTC, felix642 commented on src/DFT.h
> +    #define M_PI 3.14159265358979323846
Why don't you use the PI from <math.h> ?

2023-02-03 21:50 UTC, felix642 commented on src/FFT.c
> +static int isPowerOfTwo(const unsigned value) {
This function is small enough to be declared inline. I'm pretty sure that the compiler is already inlining it since we're online using it once, but it never hurts to add a bit more info just in case.

2023-02-03 21:50 UTC, felix642 commented on src/FFT.c
> +    while (k <= j) {
I'm not quite sure to understand what is happening from lines 19-25. Could you please give me a general idea about this code?

2023-02-03 21:50 UTC, felix642 commented on src/FFT.c
> +    return 0;
0 usually means a successful operation. I think it would be better to return something else.

2023-02-03 21:50 UTC, felix642 commented on src/FFT.h
> +    #define M_PI 3.14159265358979323846
Same as above

2023-02-03 21:50 UTC, felix642 commented on tests/test_FFT.c
> +  fft_real* fftReals = calloc(length, sizeof(fft_real));
I do not think we need calloc here.

2023-02-03 21:50 UTC, felix642 commented on tests/test_FFT.c
> +  // limit length to 8 for faster testing
Limit length to 8 yet length is equal to 4 ?

2023-02-03 21:50 UTC, felix642 commented on tests/test_FFT.c
> +  fft_real* fftReals = calloc(length, sizeof(fft_real));
Those calloc are also useless.

2023-02-03 21:50 UTC, felix642 commented on tests/test_FFT.c
> +  fftReals[0] = 8;
You should declare you arrays on one lime this will be easier to read afterwards.
`fftReals[] = {8, 4, 8, 0};`

2023-02-03 23:26 UTC, bisson2000 commented on src/DFT.h
> +    #define M_PI 3.14159265358979323846
Because it is not standard and `#define _USE_MATH_DEFINES` is not working

2023-02-03 23:27 UTC, bisson2000 commented on src/FFT.h
> +    #define M_PI 3.14159265358979323846
See above

2023-02-03 23:30 UTC, bisson2000 commented on src/FFT.c
> +    return 0;
0 for false, 1 for true
exit code 0 is successful, exit code 1 is unsuccessful.
What else would you suggest

2023-02-03 23:38 UTC, bisson2000 commented on src/FFT.c
> +    while (k <= j) {
It calculates the reversed address. I am not the best at explaining it, but here is a link to a good explanation [https://dsp.stackexchange.com/questions/8804/bit-reverse-order-technique-in-fft](https://dsp.stackexchange.com/questions/8804/bit-reverse-order-technique-in-fft)

2023-02-04 01:26 UTC, felix642 commented on src/FFT.c
> +    while (k <= j) {
Thank you for the reference :)

2023-02-04 01:28 UTC, felix642 commented on src/FFT.c
> +    return 0;
From what I can see here 0 is currently unsuccessful and 1 is successful.

Unless I am missing something?

2023-02-04 12:14 UTC, bisson2000 commented on src/FFT.c
> +    return 0;
This is exactly what it does. I am returning 0 as false, and 1 as true, since booleans are not included

2023-02-04 14:26 UTC, felix642 commented on src/FFT.c
> +    return 0;
Since booleans does not exist C function will usually return 0 on success and -1 on error. Let's follow this standard otherwise, it might be confusing for people using this function. They will call it, and receive a code 1 which they think is an error but actually means that the operation was successful 

To illustrate my point here are a few functions that follow this convention : 

int catclose(nl_catd catd); 
Upon successful completion, catclose() returns 0. Otherwise -1 is returned, and errno is set to indicate the error.
 
int ferror(FILE *stream); 
If the error indicator associated with the stream was set, the function returns a non-zero value else, it returns a zero value.

int fseek(FILE *stream, long int offset, int whence); 
This function returns zero if successful, or else it returns a non-zero value.

int remove(const char *filename);
On success, zero is returned. On error, -1 is returned, and errno is set appropriately.

If you really want to use booleans then I suggest you include stdbool.h and use the true/false values

2023-02-04 14:53 UTC, felix642 commented on tests/test_FFT.c
> +  start = clock();
Is this really useful? I doubt that the algorithm is taking enough time to really see a difference. Especially if you display seconds. I'm assuming it'll say something like "The elapsed time for the FFT is 0.000001s" or something like that and then it will display the same message for the DFT no?

2023-02-04 22:24 UTC, florenceCloutier commented on tests/test_DFT.c
> +  unsigned length = 4;
const unsigned?

2023-02-04 22:24 UTC, florenceCloutier commented on tests/test_DFT.c
> +  unsigned length = 4;
Same here?

2023-02-05 00:38 UTC, bisson2000 commented on tests/test_FFT.c
> +  start = clock();
There is a major difference. Tests can have vectors with lengths up to 2**8
![image](https://user-images.githubusercontent.com/43078187/216795522-5e96c587-cc65-4ac8-8bc8-80726e990154.png)

2023-02-05 17:18 UTC, felix642 approved these changes
LGTM

2023-02-05 18:15 UTC, bisson2000 commented
Opened on offical repo instead

2023-02-05 18:15 UTC, closed without merging